#!/bin/bash
#PBS -N restore_H
#PBS -P au88
#PBS -q hugemem
#PBS -l walltime=02:00:00
#PBS -l ncpus=48
#PBS -l mem=1450GB
#PBS -l storage=gdata/au88+gdata/vk83+gdata/av17
#PBS -l wd
#PBS -o /g/data/au88/jh7060/ACCESS-AIS3/config/launch_restore_floored_thickness.pbs.out
#PBS -e /g/data/au88/jh7060/ACCESS-AIS3/config/launch_restore_floored_thickness.pbs.err
unset PYTHONPATH PYTHONSTARTUP PYTHONHOME
cd /g/data/au88/jh7060/ACCESS-AIS3/config
/scratch/au88/jh7060/mamba/envs/pyissm/bin/python -u restore_floored_thickness.py
