#!/bin/bash
#PBS -N check_relax_prop
#PBS -P au88
#PBS -q normal
#PBS -l walltime=01:00:00
#PBS -l ncpus=8
#PBS -l mem=190GB
#PBS -l storage=gdata/au88+gdata/vk83+gdata/av17
#PBS -l wd
#PBS -o /g/data/au88/jh7060/ACCESS-AIS3/config/launch_check_relaxed_geometry_propagation.pbs.out
#PBS -e /g/data/au88/jh7060/ACCESS-AIS3/config/launch_check_relaxed_geometry_propagation.pbs.err
unset PYTHONPATH PYTHONSTARTUP PYTHONHOME
cd /g/data/au88/jh7060/ACCESS-AIS3/config
/scratch/au88/jh7060/mamba/envs/pyissm/bin/python -u check_relaxed_geometry_propagation.py
