#!/bin/bash
#PBS -N plot_melt_final
#PBS -P au88
#PBS -q normal
#PBS -l walltime=00:45:00
#PBS -l ncpus=8
#PBS -l mem=190GB
#PBS -l storage=gdata/au88+gdata/vk83+gdata/av17
#PBS -l wd
#PBS -o /g/data/au88/jh7060/ACCESS-AIS3/config/launch_plot_final_melt_calibration.pbs.out
#PBS -e /g/data/au88/jh7060/ACCESS-AIS3/config/launch_plot_final_melt_calibration.pbs.err
unset PYTHONPATH PYTHONSTARTUP PYTHONHOME
cd /g/data/au88/jh7060/ACCESS-AIS3/config
/scratch/au88/jh7060/mamba/envs/pyissm/bin/python -u plot_final_melt_calibration.py
