#!/bin/bash
#PBS -N salvage_ho_relaxed
#PBS -P au88
#PBS -q hugemem
#PBS -l walltime=03:00:00
#PBS -l ncpus=48
#PBS -l mem=1450GB
#PBS -l storage=gdata/au88+gdata/vk83+gdata/av17
#PBS -l wd
#PBS -o /g/data/au88/jh7060/ACCESS-AIS3/config/launch_salvage_ho_relaxed.pbs.out
#PBS -e /g/data/au88/jh7060/ACCESS-AIS3/config/launch_salvage_ho_relaxed.pbs.err
unset PYTHONPATH PYTHONSTARTUP PYTHONHOME
cd /g/data/au88/jh7060/ACCESS-AIS3/config
/scratch/au88/jh7060/mamba/envs/pyissm/bin/python -u salvage_ho_relaxed.py
