#!/bin/bash
#PBS -N ssa_deltaT_refit
#PBS -P au88
#PBS -q normal
#PBS -l walltime=01:00:00
#PBS -l ncpus=8
#PBS -l mem=190GB
#PBS -l storage=gdata/au88+gdata/vk83+gdata/av17
#PBS -l wd
#PBS -o /g/data/au88/jh7060/ACCESS-AIS3/config/launch_ssa_melt_deltaT_basin_refit.pbs.out
#PBS -e /g/data/au88/jh7060/ACCESS-AIS3/config/launch_ssa_melt_deltaT_basin_refit.pbs.err
unset PYTHONPATH PYTHONSTARTUP PYTHONHOME
cd /g/data/au88/jh7060/ACCESS-AIS3/config
/scratch/au88/jh7060/mamba/envs/pyissm/bin/python -u ssa_melt_deltaT_basin_refit.py
